image: gitpod/workspace-postgres

tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 5173`
      npm run dev
    env:
      DATABASE_URL: postgres://gitpod@localhost/energieverbrauch
  - command: npx prisma studio
    env:
      DATABASE_URL: postgres://gitpod@localhost/energieverbrauch

ports:
  - port: 5173
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
  - port: 5555
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode

    - Prisma.prisma

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
